apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-hello-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-hello-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
