name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  IMAGE_NAME: python-hello-service

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
          poetry install --with dev --no-interaction --no-ansi

      - name: Run Tests
        run: |
          pip install pytest pytest-cov junit-xml
          pytest --junitxml=test-results.xml

      - name: Upload Test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry and Coverage Tool
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
          poetry install --with dev --no-interaction --no-ansi
          pip install coverage

      - name: Run Coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload Coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry and Flake8
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
          poetry install --only main --no-interaction --no-ansi
          pip install flake8

      - name: Run Flake8
        run: flake8 --format=checkstyle --output-file=flake8-report.xml . || true

      - name: Upload Flake8 artifact
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8-report.xml