name: python-hello-service

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  call-template:
    uses: jlmOrg/cicd-templates/.github/workflows/python-cicd-template.yml@7-ecr-connectivity
    with:
      image-name: python-hello-service
      python-version: '3.13'
      ecr-registry: '550487074477.dkr.ecr.us-east-1.amazonaws.com'