name: python-hello-service

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  call-template:
    uses: jlmOrg/cicd-templates/.github/workflows/python-cicd-template.yml@11-reference-helm-chart
    with:
      image-name: python-hello-service
      python-version: '3.13'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EKS_DEV_CLUSTER_NAME: ${{ secrets.EKS_DEV_CLUSTER_NAME }}
